name: national-diet-search

services:

  server:
    container_name: national-diet-search-server
    hostname: national-diet-search-server
    ports:
        - 8080:8080
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./container-mount:/workspace/container-mount:cached
